### ISSUE TITLE
Support for globbing of inputs

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/SignService#10]
It would be nice to be able to just add a directory and have all the inputs be included. For instance, if I use `dotnet pack` to generate a package, I don't necessarily know the full name. If I could then run `dotnet SignClient.dll zip --config [path] -i Package.*.nupkg` that would be really nice.

**Comment by onovotny** [comment]
Thinking more about this, what should it do if there's more than one match? There's an output file option too, should it be allowed only if there's a single matching input?

The workaround to this is that the script uses the full name or for multiple files, can put it in a zip file and send that.

Also, if a filter is needed, there's no current way of mapping that to a file; it'd be the same filter for all inputs.

How would you expect it to work?
