### ISSUE TITLE
Does not work on machines that have only v3 SDK installed

### ISSUE THREAD

**Issue by leastprivilege** [dotnet/SignService#117]
IOW - the global tool needs a 2.x runtime.

This can be fixed by either enabling roll forward for the 2.x tool - or provide a version that is compiled against v3.

Error:

Tool 'signclient' (version '1.1.53') was successfully installed.
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.2.0' was not found.
  - The following frameworks were found:
      3.0.0 at [/opt/hostedtoolcache/dotnet/shared/Microsoft.NETCore.App]

**Comment by onovotny** [comment]
Will get that fixed asap

**Comment by onovotny** [comment]
Hmm....that version already has `rollForward` in its runtimeconfig.json file. It's also targeting netcoreapp2.1. Do you have a repro for this?

**Comment by leastprivilege** [comment]
https://dev.azure.com/netidentity/IdentityModel/_build/results?buildId=990

**Comment by leastprivilege** [comment]
for the time being I installed 2.x SDK which seems to fix the problem

https://dev.azure.com/netidentity/IdentityModel/_build/results?buildId=991

**Comment by onovotny** [comment]
The issue is your build project, not SignClient:
https://github.com/IdentityModel/IdentityModel/blob/master/build/build.csproj 
It's `netcoreapp2.2`.

The UseDotNet command needs to have both -- you at least need to install the 2.2 runtime (does not need the sdk) as well.

**Comment by leastprivilege** [comment]
doh ;) thanks!

**Comment by leastprivilege** [comment]
I misread that. Sorry.

**Comment by onovotny** [comment]
Easy to miss :)
