### ISSUE TITLE
Exit code 0 when no files found to sign

### ISSUE THREAD

**Issue by AArnott** [dotnet/SignService#197]
When the .nupkg file is not where I indicate it should be found:

```
dotnet tool run SignClient -- sign --baseDirectory D:\git\Nerdbank.GitVersioning\bin\Nerdbank.GitVersioning.Tasks\Release --input "*.nupkg" ...
```

The tool simply returns with exit code 0 and does not emit any warning whatever. Yet surely if I invoke the tool and it signs nothing, that's a cause for concern, is it not?

Shouldn't the tool write a warning to stderr and return a non-zero exit code?

**Comment by onovotny** [comment]
Good point, signing nothing is probably flag that the inputs weren't correctly found. 

Any chance you can submit a PR?
