### ISSUE TITLE
Build break on Registry types

### ISSUE THREAD

**Issue by AArnott** [dotnet/SignService#199]
I don't know how this is building in Azure Pipelines. The SignService is targeting netcoreapp3.1 but not referencing the `Microsoft.Win32.Registry` package. So local builds fail with this:

```
Utils\mansign2.cs(877,27): error CS0103: The name 'Registry' does not exist in the current context [D:\git\SignService\src\SignService\SignService.csproj] Utils\mansign2.cs(881,33): error CS0103: The name 'RegistryValueKind' does not exist in the current context [D:\git\SignService\src\SignService\SignService.csproj]
Utils\mansign2.cs(881,68): error CS0103: The name 'RegistryValueKind' does not exist in the current context [D:\git\SignService\src\SignService\SignService.csproj]
```

Is this really a configuration fail on my part somehow?

I'd like to send a PR that fixes the build break on my machine. I'd just feel better knowing how it works for anybody else.

**Comment by clairernovotny** [comment]
This is because of a bug in the 302 SDK.

**Comment by AArnott** [comment]
I stand corrected. [It _does_ fail](https://dev.azure.com/clairernovotny/GitBuilds/_build/results?buildId=3262&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=006e6f7c-8314-5e02-a3df-483f3a1f4cfa&l=19) in Azure Pipelines before my fix.
