### ISSUE TITLE
ArmDeploy failure

### ISSUE THREAD

**Issue by andrewmolyneux** [dotnet/SignService#213]
OK, I'm way out of my depth here but I'm trying to follow the deployment guide. I got to step 3a (ARM template) and it deployed OK the first time I tried it from VS2019, but the web app name I chose the first time was wrong so I needed to change the name and redeploy from scratch. I thought I could do this by deleting the resource group that I created for the SignService app and deploying again from Visual Studio, but every time I try to deploy I get this error:
```
17:29:58 - New-AzureRmResourceGroupDeployment : 17:29:58 - Resource Microsoft.Web/sites/siteextensions 
17:29:58 - '<siteName>/Microsoft.ApplicationInsights.AzureWebSites' failed with message '{
17:29:58 -   "status": "Canceled",
17:29:58 -   "error": {
17:29:58 -     "code": "ResourceDeploymentFailure",
17:29:58 -     "message": "The resource operation completed with terminal provisioning state 'Canceled'."
17:29:58 -   }
17:29:58 - }'
```
Any help would be gratefully received :)

**Comment by clairernovotny** [comment]
I'm not sure.... are things completely deleted in Azure? Might take some time for things to finish deleting.

**Comment by andrewmolyneux** [comment]
Thanks Claire. I tried leaving it a couple of hours between deleting the resource group and deploying again, and still got the error. I've deleted the RG again now so I'll leave it over the weekend and try again on Monday :)

**Comment by clairernovotny** [comment]
Happy to jump on a call early next week if it's still not working. Getting things deployed for this is unfortunately the hardest part.

**Comment by andrewmolyneux** [comment]
That's extremely kind of you - I'll let you know if I'm still stuck on Monday.

**Comment by andrewmolyneux** [comment]
Yep, it seems it just needed to be left for a while after deleting the RG. All good now, thanks :)
