### ISSUE TITLE
Is it possible to sign ClickOnce manifest files when certificate private key is in HSM?

### ISSUE THREAD

**Issue by andrewmolyneux** [dotnet/SignService#214]
I've been trying to deploy SignService (issue #213) but now I'm looking at the code in MageSignService.cs and I have a horrible feeling it's not going to work for us anyway. The CA that issued our code signing certificate insisted on the private key being in HSM (key type is RSA-HSM), so I don't believe we have access to the private key at all. The code in MageSignService.cs looks like it needs to extract the private key from Key Vault to pass it to mage.exe, which I'm guessing won't be possible as the key isn't exportable. Is this correct?

**Comment by clairernovotny** [comment]
That's not correct. The entire signing service uses RSA-HSM keys in Key Vault. It uses an RSA implementation that delegates the signing operations to Key Vault.

**Comment by andrewmolyneux** [comment]
That's a huge relief, thanks Claire!
