### ISSUE TITLE
Clickonce time stamping manifest XML

### ISSUE THREAD

**Issue by vr333dev** [dotnet/SignService#239]
Hello, I am having trouble with time stamping license DOM when using clickonce functionality.  This is happening whether signedXml.CheckSignature(Key) returns true or false.  The actual line of code that returns an error value is this: var hr = Win32.CertTimestampAuthenticodeLicense(ref licenseBlob, timeStampUrl, ref timestampBlob);

Would it be possible to provide an alternative way of time stamping license DOM, or is there a way to better debug this type of issue please? I tried different formats of manifest XML and nothing seemed to work.

Thanks

Vlad

**Comment by vr333dev** [comment]
Resolved by calling the crypt32 timestamp method, where the original time stamp logic is used in the "catch" block, for a fallback.  

Source: https://github.com/microsoft/msbuild/commit/0551aa0c27b7d1b371ada34c65f6fdb56ba2a9b8

**Comment by phkodo** [comment]
Hi @vr333dev 
I have the same issue with ClickOnce and a timestamp. But I did not get the msbuild merge running.
Can you please provide me your sample code?
Thanks in advance! :)
