### ISSUE TITLE
Missing dependency in azuredeploy.json

### ISSUE THREAD

**Issue by mgiles** [dotnet/SignService#264]
Hi, thanks for maintaining this project. It's been extremely helpful for me in moving some code signing off-premises and into Azure.

When deploying the `ArmDeploy` project, I get the following error:

```
Deployment template validation failed: 'The resource 'Microsoft.Web/Sites/SignService/siteextension/Microsoft.ApplicationInsights.AzureWebSites' is not defined in the template
```

It looks like this is because in a [recent commit](https://github.com/dotnet/SignService/commit/908dab55c66a2e37b4e9d1b62db3f47293caf092), the `Microsoft.ApplicationInsights.AzureWebSites` resource was removed from the template, but that resource is still referenced in the `dependsOn` clause for the [Microsoft.AspNetCore.AzureAppServices.SiteExtension](https://github.com/dotnet/SignService/blob/master/arm/ArmDeploy/azuredeploy.json#L167) resource.

I'm very new to ARM templates, and Azure generally, so I'm not sure what the best fix is. To get my deployment working I just removed that `dependsOn` line, as it looked like the `Microsoft.AspNetCore.AzureAppServices.SiteExtension` was important to keep but does on actually need the Application Insights resource.

If that's the correct fix, I'm happy to open a PR with the change. Otherwise please let me know if there's a better solution 🙂 

Thanks!

**Comment by clairernovotny** [comment]
The templates haven't gotten a lot of attention -- the app insights website extension isn't required anymore and can be removed from the template.
