### ISSUE TITLE
AzureAd.Instance in appsettings.json

### ISSUE THREAD

**Issue by mgiles** [dotnet/SignService#265]
When I run `InstallUtility` and log in with my Microsoft account, I get the following error:

```
Microsoft Accounts's with the common endpoint are not supported. Update appsettings.json with your tenant-specific endpoint
```

I believe [this issue](https://github.com/dotnet/SignService/issues/30) describes the same thing.

I was able to move forward by changing the `AzureAd.Instance` field in `appsettings.json` from `https://login.microsoftonline.com/common` to `https://login.microsoftonline.com/{my AD tenant ID}`. This seems to work fine for running `InstallUtility`, and code-signing ends up working fine, but I'm wondering if it indicates I'm setting something up wrong. Should I anticipate running into any issues, having made this change?

**Comment by clairernovotny** [comment]
Nope, that's totally fine. /common is just a short-hand so I didn't have to code per tenant.

**Comment by mgiles** [comment]
Great, thanks 👌
