### ISSUE TITLE
CryptoConfigShims incorrectly calls an internal .NET core method using reflection

### ISSUE THREAD

**Issue by mgiles** [dotnet/SignService#266]
When attempting to sign a VSTO ClickOnce archive, I encounter the following error:

`Late bound operations cannot be performed on types or methods for which ContainsGenericParameters is true.`

In my case, this is being raised from [line 35 in CryptoConfigShims](https://github.com/dotnet/SignService/blob/2438cd2a9ef8fbfd77d3293fc6eb2cf883225a03/src/SignService/Utils/CryptoConfigShims.cs#L35):

`var item = (AsymmetricSignatureFormatter)CryptoHelpersCreateFromName.Invoke(null, new object[] { FormatterAlgorithm });`

Where `CryptoHelpersCreateFromName` is fetched from an internal .NET core assembly using reflection:

```
var helperType = Type.GetType("System.Security.Cryptography.Xml.CryptoHelpers, System.Security.Cryptography.Xml");
CryptoHelpersCreateFromName = helperType.GetTypeInfo().GetDeclaredMethod("CreateFromName");
```

I believe the error is being raised because, in current versions of .NET core, the `CreateFromName` method is generic, but the generic type parameter is not being instantiated before the method is `Invoke`'d. It looks to me like originally, when this code was written, the method was _not_ generic, but in [.NET core 2.0.8](https://github.com/dotnet/corefx/commit/8f968b9e79c5721d78cc88e46fe57457fe9d490d#diff-3da36149acec1a6d9bed3152a1600191R85) it was made generic.

As a workaround, I changed the call to the public method [CryptoConfig.CreateFromName](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/CryptoConfig.cs#L449), and this seemed to make signing work correctly in my case. This has slightly different behaviour than the old reflection call, though.

I have a few ideas for fixes, but would appreciate some guidance:

1. Update the existing code to instantiate the generic parameter before `Invoke`ing the method. This would most closely match the previous behaviour, but would still depend on an internal method that may unexpectedly change again in the future.
2. Call a different, public method like `CryptoConfig.CreateFromName` (I have _no_ idea if the change in behaviour is important!)
3. Reproduce the code from the internal `CryptoHelpers` class inside this project, to keep the previous behaviour without needing to call the internal code

I lean towards the third option, but am unsure. I'm happy to open a PR for any of these, or a different solution. Any thoughts on the best approach?

**Comment by clairernovotny** [comment]
Thanks for looking into this. I'm sure you're right in your analysis as this code hasn't been touched in a long time. I'm sure that changes in the underlying runtime broke this.

I'm not sure if the change in behavior is relevant? If you're able to get it working and have VSTO working, then that's all that really matters, I think. I'd gladly take a PR.
