### ISSUE TITLE
Clickonce fails if filelist does not include .manifest

### ISSUE THREAD

**Issue by tbolon** [dotnet/SignService#355]
Because MageSignService uses FilteredFilesInDirectory to find the .manifest, the [.Single()](https://github.com/dotnet/SignService/blob/main/src/SignService/SigningTools/MageSignService.cs#L138) method call will fail if you use a filelist.txt and forget to include the .manifest file.

We should either 1) update the readme with a warning or a minimal required filelist content, or 2) update the code to use FilesInDirectory instead of FilteredFilesInDirectory.

My suggestion is for 2). I can submit a PR if you want.

PS: I also have troubles collecting application insight details. The only way to track requests is to use the Live metrics view. All others views returns 0 results.

**Comment by clairernovotny** [comment]
Happy to take a PR to make this better!

**Comment by tbolon** [comment]
Done :)
