### ISSUE TITLE
Directory.ReadWrite.All permission

### ISSUE THREAD

**Issue by 08Leinad08** [dotnet/SignService#391]
Is there an alternative configuration to granting the SignService Server app registration the "Directory.ReadWrite.All" permission in the tenant? In our corporate environment, granting this permission is not ideal.

**Comment by clairernovotny** [comment]
Unfortunately, that's required for some of the functionality. One option is to create a new AAD tenant for this and assign an azure sub to it. That keeps this isolated from the main corporate tenant.

**Comment by clairernovotny** [comment]
Closing due to age.
