### ISSUE TITLE
Error: Vault xxxx is not in the correct resource group. Cannot view details here.

### ISSUE THREAD

**Issue by yowl** [dotnet/SignService#394]
When trying to create a CSR for a premium key vault (HSM is the destination), this message is displayed.

Following the recommended instructions I don't think is correct for HSM certs as if you let the sign server create the key vault it will create a standard key vault which is not correct for HSM.  So I created the KeyVault from the portal, then set it to the user using the KeyVaultUrl, but now I'm unable to use the Sign Server to create the CSR.  Any idea what I've done wrong?

I think the resource group is correct, because if any other resource group is picked for the KeyVault, then it wont show in the SignServer app.

**Comment by clairernovotny** [comment]
Hi @yowl it's likely a permissions thing. The permissions on the resource groups and vaults are extremely sensitive and need to be correct. It's recommended that you create the user (and their associated key vault) through the website as that's the way to ensure things are set up correctly.

The service only creates premium vaults:
https://github.com/dotnet/SignService/blob/main/src/SignService/Services/KeyVaultAdminService.cs#L135

And it's hard-coded for HSM-ony key types, which are required for EV certificatres.

**Comment by yowl** [comment]
@clairernovotny Thanks for the link.  I don't know where I got that it would create a standard SKU vault,
