### ISSUE TITLE
Question: Merging certificate using the Admin UI

### ISSUE THREAD

**Issue by yowl** [dotnet/SignService#401]
Hi,

I have my EV code signing certificate from Digicert and now want to complete the merge using the UI and tip 1 here https://github.com/dotnet/signservice.

Digicert have issued a zip with 3 `.crt` files.  My certificate, the code signing issuer `CN = DigiCert Trusted G4 Code Signing RSA4096 SHA384 2021 CA1` and the trusted root.  Should I merge (concatenate) the 3 `.crt` files and upload that, or just the `.crt` for our CN?

**Comment by clairernovotny** [comment]
You only need the one with your CN; the others are intermediates/roots.

**Comment by yowl** [comment]
Thanks!
