### ISSUE TITLE
Question: Is it possible to sign manifest and vsto files that are not part of ClickOnce?

### ISSUE THREAD

**Issue by keerp2952** [dotnet/SignService#419]
I am trying to distribute VSTO Excel add-in applications without using `ClickOnce`.
Is it possible to sign `.vsto` and `.manifest` files using `mage` in `SignService`?
I was wondering if operations like these are supported. [Re-sign the Application and Deployment Manifests](https://docs.microsoft.com/en-us/visualstudio/deployment/how-to-re-sign-application-and-deployment-manifests?view=vs-2022)
Thanks! :)

**Comment by clairernovotny** [comment]
I haven't tried, but it should work. Have you tried zipping it up the files and renaming it to `.clickonce` (just so the service takes it down the right code path).

**Comment by keerp2952** [comment]
Thank you. I was able to sign the code successfully based on the suggestion.
