### ISSUE TITLE
SignService server: error while signing "The application has failed to start because its side-by-side configuration is incorrect"

### ISSUE THREAD

**Issue by Aaronontheweb** [dotnet/SignService#67]
While trying to update our SignService instance to the most recent `master` branch code per https://github.com/dotnet/SignService/issues/60#issuecomment-489245289, ran into the following error running the latest code:

The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detailSystem.ComponentModel.Win32Exception (14001): The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detailat SignService.Utils.Kernel32.ActivationContext..ctor(String assemblyName) in d:\a\1\s\src\SignService\Utils\Kernel32.cs:line 77at SignService.AzureSignToolSignService.RunSignTool(AuthenticodeKeyVaultSigner signer, String file, String description, String descriptionUrl) in d:\a\1\s\src\SignService\SigningTools\AzureSignToolSignService.cs:line 105

I deployed to our Azure Website that we've been using to host the SignService instance using an artifact deployment via the https://github.com/dotnet/SignService/blob/master/azure-pipelines.server.yml file in this repository.

Is this a configuration issue with my specific deployment? Or an issue with the latest code?

**Comment by onovotny** [comment]
Are you hosting this on App Services or a VM? How are you building it? I have 1.1.15 running without incident so far on App Services.

**Comment by Aaronontheweb** [comment]
App services - built using your pipelines script on Azure pipelines. Deploying the artifact created from that script directly to the App Service

**Comment by onovotny** [comment]
That's quite unusual, I woudln't expect that. Can you try to redeploy? Also, verify that in the deployment zip, that the various dll/manifest files are in the tools dir

**Comment by Aaronontheweb** [comment]
Will do - I’ll check

**Comment by Aaronontheweb** [comment]
![image](https://user-images.githubusercontent.com/326939/57185531-c3287580-6e92-11e9-8626-c2ba03bd24c3.png)

**x86**
![image](https://user-images.githubusercontent.com/326939/57185536-cde30a80-6e92-11e9-8cb7-d1a215d822e5.png)

**x64**
![image](https://user-images.githubusercontent.com/326939/57185538-d3d8eb80-6e92-11e9-9013-c5d181039da5.png)

Does this look right? Based on the contents of the .zip

**Comment by Aaronontheweb** [comment]
Additional issue at startup:

```
2019-05-04 22:39:09.099 +00:00 [Critical] Microsoft.AspNetCore.Hosting.Internal.WebHost: Hosting startup assembly exceptionSystem.InvalidOperationException: Startup assembly StartupBootstrapper failed to execute. See the inner exception for more details. ---> System.IO.FileNotFoundException: Could not load file or assembly 'StartupBootstrapper, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)at System.Reflection.Assembly.Load(AssemblyName assemblyRef)at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)--- End of inner exception stack trace ---
```

**Comment by Aaronontheweb** [comment]
Wonder if the issue is that `Environment.GetEnvironmentVariable("REGION_NAME"))` isn't returning a value for some reason.

**Comment by Aaronontheweb** [comment]
Nope, Azure Web Console revealed that I have both `REGION_NAME2` and `HOME_EXPANDED` defined

**Comment by Aaronontheweb** [comment]
Resolved the startup issue by following some of the advice here https://github.com/aspnet/AspNetCore/issues/5919

**Comment by Aaronontheweb** [comment]
Still having the SXS failure though even after a re-deployment and fixing the .NET Core 2.2 extensions on the Azure App Services instance.

**Comment by Aaronontheweb** [comment]
Could the issue be, per the previous screenshots, is that the necessary DLLs and `signservice.exe` were never copied off of the Azure Pipelines build agent and onto the machine. I see the manifest files, but none of the DLLs themselves?

**Comment by Aaronontheweb** [comment]
although it looks like that's done intentionally here:

https://github.com/dotnet/SignService/blob/c5b1c3de1f61a3b849bcad7dd8e1ae2ab9bdca77/src/SignService/SignService.csproj#L29-L60

**Comment by Aaronontheweb** [comment]
Validated the contents via the build artifacts I downloaded from Azure Pipelines - all of the DLLs referenced in the manifests are there.

**Comment by Aaronontheweb** [comment]
Got everything working on my end finally - I think the issue was how we're doing the Azure App Service deployment from Azure Pipelines. I'd recommend we take your advice from the Twitter thread we had earlier and add that to the development documentation:

https://twitter.com/onovotny/status/1125771206529961985

> On the deployment, I always configure a slot and ensure the right settings are pinned to the prod slot. In the tasks, I stop the deployment slot, deploy, start, then do a slot swap. Makes sure nothing is in use.

I'm certain my issue was caused by a dirty deployment. But it's happily code-signing away now.

**Comment by andrewmolyneux** [comment]
Apologies for playing necromancer here, but I've just deployed SignService to an App Service (on a B1 instance) and I'm seeing exactly the same problem. I saw the advice about using a deployment slot but it seems B1 instances don't support deployment slots, so I scaled up to S1 and did the following:
- Created a slot named "staging" (copying the settings from production)
- Stopped the "staging" slot
- Deployed (using Azure Pipelines)
- Started the "staging" slot
- Swapped "staging" with "production"

I still can't get it to sign anything at all - it's consistently failing with the same "Sxs config is incorrect" error - and I'm beginning to lose the will to live 😆
Help me @clairernovotny, you're my only hope!
