### ISSUE TITLE
SignClient not compatible with 3.0 pre5

### ISSUE THREAD

**Issue by dansiegel** [dotnet/SignService#72]
When adding the 3.0 pre5 sdk on an Azure Pipelines Agent, the SignClient cannot execute with an error that it cannot find any compatible framework.

```
You can invoke the tool using the following command: SignClient 
Tool 'signclient' (version '1.1.7') was successfully installed.
##[error].\SignClient : It was not possible to find any compatible framework version
```

**Comment by onovotny** [comment]
Needs an update to support https://github.com/dotnet/designs/blob/master/accepted/runtime-binding.md#rollforward

**Comment by onovotny** [comment]
Fixed by https://github.com/dotnet/SignService/commit/b815d6ca4e3f265fa0db270d61dd23a2ce4cf019

Client version 1.1.21 is rolling out to NuGet now with the fix

**Comment by dansiegel** [comment]
thanks @onovotny
