### ISSUE TITLE
Getting errors returning large files

### ISSUE THREAD

**Issue by onovotny** [dotnet/SignService#97]
Something is going on with larger files, 160 megs or so.

https://github.com/dotnet/SignService/blob/ae636bb5757ba6d521cde42eedcffc33f17e7a38/src/SignService/Controllers/SignController.cs#L75-L93

![image](https://user-images.githubusercontent.com/1427284/62828440-6be22180-bbb4-11e9-9eae-8913530d0186.png)

**Comment by onovotny** [comment]
Calling code:

https://github.com/reactiveui/refit/blob/0ad0357173d4be60294a8866fae4e560c5a9d2ee/Refit/RequestBuilderImplementation.cs#L250

https://github.com/dotnet/SignService/blob/ae636bb5757ba6d521cde42eedcffc33f17e7a38/src/SignClient/SignCommand.cs#L117-L133

**Comment by Tratcher** [comment]
Full server logs?

Are you sure it's not just throwing OutOfMemory or similar? This code is loading the whole file into memory at least twice:
https://github.com/dotnet/SignService/blob/ae636bb5757ba6d521cde42eedcffc33f17e7a38/src/SignService/Controllers/SignController.cs#L74-L84
https://github.com/dotnet/corefx/blob/b129f7657a1b93ce9cf577d769d9d03c862e2338/src/Common/src/CoreLib/System/IO/MemoryStream.cs#L624-L632

**Comment by onovotny** [comment]
I think that's likely, that code was never great. @benaadams was kind enough to help rewrite it to avoid putting the file entirely in memory. I'll close this out and reopen if it happens again now.
